name: trigger jenkins job
on: 
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 60 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://7fb02167.ngrok.io"
        user: "admin"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "trigger-coffee-una-dev"
