name: trigger jenkins job
on: 
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://3afb4e34.ngrok.io/"
        user: "admin"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "trigger-coffee-una-dev"
